=== gluehloch/bo-testutils/src/main/resources/de/betoffice/database/test/database-master.dtd
<!ELEMENT dataset (
    bo_grouptype*,
    bo_team*,
    bo_teamalias*,
    bo_user*)>

<!ELEMENT bo_game EMPTY>
<!ATTLIST bo_game
    id CDATA #REQUIRED
    bo_date CDATA #IMPLIED
    bo_group_ref CDATA #IMPLIED
    bo_hometeam_ref CDATA #IMPLIED
    bo_guestteam_ref CDATA #IMPLIED
    bo_homegoals CDATA #IMPLIED
    bo_guestgoals CDATA #IMPLIED
    bo_isplayed CDATA #IMPLIED
    bo_gamelist_ref CDATA #IMPLIED
    bo_index CDATA #IMPLIED
    bo_datetime CDATA #IMPLIED
>

<!ELEMENT bo_gamelist EMPTY>
<!ATTLIST bo_gamelist
    id CDATA #REQUIRED
    bo_index CDATA #IMPLIED
    bo_date CDATA #IMPLIED
    bo_season_ref CDATA #IMPLIED
    bo_group_ref CDATA #IMPLIED
    bo_datetime CDATA #IMPLIED
>

<!ELEMENT bo_gametipp EMPTY>
<!ATTLIST bo_gametipp
    id CDATA #REQUIRED
    bo_homegoals CDATA #IMPLIED
    bo_guestgoals CDATA #IMPLIED
    bo_user_ref CDATA #IMPLIED
    bo_game_ref CDATA #IMPLIED
    bo_status CDATA #IMPLIED
    bo_tipps_index CDATA #IMPLIED
>

<!ELEMENT bo_group EMPTY>
<!ATTLIST bo_group
    id CDATA #REQUIRED
    bo_season_ref CDATA #REQUIRED
    bo_grouptype_ref CDATA #REQUIRED
>

<!ELEMENT bo_grouptype EMPTY>
<!ATTLIST bo_grouptype
    id CDATA #REQUIRED
    bo_name CDATA #REQUIRED
>

<!ELEMENT bo_season EMPTY>
<!ATTLIST bo_season
    id CDATA #REQUIRED
    bo_exportdirectory CDATA #IMPLIED
    bo_exporttemplate CDATA #IMPLIED
    bo_year CDATA #IMPLIED
    bo_name CDATA #IMPLIED
    bo_current_ref CDATA #IMPLIED
    bo_mode CDATA #IMPLIED
    bo_teamtype CDATA #IMPLIED
>

<!ELEMENT bo_team EMPTY>
<!ATTLIST bo_team
    id CDATA #REQUIRED
    bo_name CDATA #REQUIRED
    bo_longname CDATA #IMPLIED
    bo_logo CDATA #IMPLIED
    bo_teamtype CDATA #IMPLIED
>

<!ELEMENT bo_team_group EMPTY>
<!ATTLIST bo_team_group
    bo_group_ref CDATA #REQUIRED
    bo_team_ref CDATA #REQUIRED
>

<!ELEMENT bo_teamalias EMPTY>
<!ATTLIST bo_teamalias
    id CDATA #REQUIRED
    bo_aliasname CDATA #REQUIRED
    bo_team_ref CDATA #REQUIRED
>

<!ELEMENT bo_user EMPTY>
<!ATTLIST bo_user
    id CDATA #REQUIRED
    bo_name CDATA #IMPLIED
    bo_surname CDATA #IMPLIED
    bo_nickname CDATA #REQUIRED
    bo_email CDATA #IMPLIED
    bo_phone CDATA #IMPLIED
    bo_password CDATA #IMPLIED
    bo_automat CDATA #IMPLIED
    bo_excluded CDATA #IMPLIED
    bo_title CDATA #IMPLIED
>

<!ELEMENT bo_user_season EMPTY>
<!ATTLIST bo_user_season
    id CDATA #REQUIRED
    bo_season_ref CDATA #REQUIRED
    bo_user_ref CDATA #REQUIRED
    bo_wager CDATA #IMPLIED
>

=== gluehloch/bo-testutils/src/main/resources/de/betoffice/database/test/masterdata.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "database-master.dtd">
<dataset>
  <bo_grouptype id="59" bo_name="Gruppe A"/>
  <bo_grouptype id="60" bo_name="Gruppe B"/>
  <bo_grouptype id="61" bo_name="Gruppe C"/>
  <bo_grouptype id="62" bo_name="Gruppe D"/>
  <bo_grouptype id="63" bo_name="Gruppe E"/>
  <bo_grouptype id="64" bo_name="Gruppe F"/>
  <bo_grouptype id="65" bo_name="Gruppe G"/>
  <bo_grouptype id="66" bo_name="Gruppe H"/>
  <bo_grouptype id="67" bo_name="Achtelfinale"/>
  <bo_grouptype id="68" bo_name="Viertelfinale"/>
  <bo_grouptype id="69" bo_name="Halbfinale"/>
  <bo_grouptype id="70" bo_name="Spiel um Platz 3"/>
  <bo_grouptype id="71" bo_name="Finale"/>
  <bo_grouptype id="72" bo_name="1. Liga"/>

  <bo_team id="27" bo_name="Frankreich" bo_longname="Frankreich" bo_logo="frankreich.gif" bo_teamtype="1"/>
  <bo_team id="28" bo_name="Senegal" bo_longname="Senegal" bo_logo="senegal.gif" bo_teamtype="1"/>
  <bo_team id="29" bo_name="Uruguay" bo_longname="Uruguay" bo_logo="uruguay.gif" bo_teamtype="1"/>
  <bo_team id="30" bo_name="Dänemark" bo_longname="Dänemark" bo_logo="daenemark.gif" bo_teamtype="1"/>
  <bo_team id="31" bo_name="Paraguay" bo_longname="Paraguay" bo_logo="paraguay.gif" bo_teamtype="1"/>
  <bo_team id="32" bo_name="Südafrika" bo_longname="Südafrika" bo_logo="suedafrika.gif" bo_teamtype="1"/>
  <bo_team id="33" bo_name="Spanien" bo_longname="Spanien" bo_logo="spanien.gif" bo_teamtype="1"/>
  <bo_team id="34" bo_name="Slowenien" bo_longname="Slowenien" bo_logo="slowenien.gif" bo_teamtype="1"/>
  <bo_team id="35" bo_name="Brasilien" bo_longname="Brasilien" bo_logo="brasilien.gif" bo_teamtype="1"/>
  <bo_team id="36" bo_name="Türkei" bo_longname="Türkei" bo_logo="tuerkei.gif" bo_teamtype="1"/>
  <bo_team id="37" bo_name="China VR" bo_longname="China VR" bo_logo="china.gif" bo_teamtype="1"/>
  <bo_team id="38" bo_name="Costa Rica" bo_longname="Costa Rica" bo_logo="costarica.gif" bo_teamtype="1"/>
  <bo_team id="39" bo_name="Rep.Korea" bo_longname="Rep.Korea" bo_logo="suedkorea.gif" bo_teamtype="1"/>
  <bo_team id="40" bo_name="Polen" bo_longname="Polen" bo_logo="polen.gif" bo_teamtype="1"/>
  <bo_team id="41" bo_name="USA" bo_longname="USA" bo_logo="usa.gif" bo_teamtype="1"/>
  <bo_team id="42" bo_name="Portugal" bo_longname="Portugal" bo_logo="portugal.gif" bo_teamtype="1"/>
  <bo_team id="43" bo_name="Irland" bo_longname="Irland" bo_logo="irland.gif" bo_teamtype="1"/>
  <bo_team id="44" bo_name="Kamerun" bo_longname="Kamerun" bo_logo="kamerun.gif" bo_teamtype="1"/>
  <bo_team id="45" bo_name="Deutschland" bo_longname="Deutschland" bo_logo="dfb.gif" bo_teamtype="1"/>
  <bo_team id="46" bo_name="Saudi Arabien" bo_longname="Saudi Arabien" bo_logo="saudiarabien.gif" bo_teamtype="1"/>
  <bo_team id="47" bo_name="England" bo_longname="England" bo_logo="england.gif" bo_teamtype="1"/>
  <bo_team id="48" bo_name="Schweden" bo_longname="Schweden" bo_logo="schweden.gif" bo_teamtype="1"/>
  <bo_team id="49" bo_name="Argentinien" bo_longname="Argentinien" bo_logo="argentinien.gif" bo_teamtype="1"/>
  <bo_team id="50" bo_name="Nigeria" bo_longname="Nigeria" bo_logo="nigeria.gif" bo_teamtype="1"/>
  <bo_team id="51" bo_name="Kroatien" bo_longname="Kroatien" bo_logo="kroatien.gif" bo_teamtype="1"/>
  <bo_team id="52" bo_name="Mexiko" bo_longname="Mexiko" bo_logo="mexiko.gif" bo_teamtype="1"/>
  <bo_team id="53" bo_name="Ecuador" bo_longname="Ecuador" bo_logo="ecuador.gif" bo_teamtype="1"/>
  <bo_team id="54" bo_name="Italien" bo_longname="Italien" bo_logo="italien.gif" bo_teamtype="1"/>
  <bo_team id="55" bo_name="Japan" bo_longname="Japan" bo_logo="japan.gif" bo_teamtype="1"/>
  <bo_team id="56" bo_name="Belgien" bo_longname="Belgien" bo_logo="belgien.gif" bo_teamtype="1"/>
  <bo_team id="57" bo_name="Russland" bo_longname="Russland" bo_logo="russland.gif" bo_teamtype="1"/>
  <bo_team id="58" bo_name="Tunesien" bo_longname="Tunesien" bo_logo="tunesien.gif" bo_teamtype="1"/>
  <bo_team id="907" bo_name="Griechenland" bo_longname="Griechenland" bo_logo="greece.gif" bo_teamtype="1"/>
  <bo_team id="911" bo_name="Schweiz" bo_longname="Schweiz" bo_logo="swiss.gif" bo_teamtype="1"/>
  <bo_team id="919" bo_name="Bulgarien" bo_longname="Bulgarien" bo_logo="bulgary.gif" bo_teamtype="1"/>
  <bo_team id="922" bo_name="Tschechien" bo_longname="Tschechien" bo_logo="czech.gif" bo_teamtype="1"/>
  <bo_team id="923" bo_name="Lettland" bo_longname="Lettland" bo_logo="lettland.gif" bo_teamtype="1"/>
  <bo_team id="924" bo_name="Niederlande" bo_longname="Niederlande" bo_logo="netherland" bo_teamtype="1"/>
  <bo_team id="1131" bo_name="[noch_nicht_bekannt]" bo_longname="[noch_nicht_bekannt]" bo_logo="unbekannt.gif" bo_teamtype="1"/>
  <bo_team id="1132" bo_name="Trinidad Tabago" bo_longname="Trinidad und Tabago" bo_logo="trinidadtabago.gif" bo_teamtype="1"/>
  <bo_team id="1133" bo_name="Elfenbeinküste" bo_longname="Elfenbeinküste" bo_logo="elfenbeinkueste.gif" bo_teamtype="1"/>
  <bo_team id="1134" bo_name="Serbien Montenegro" bo_longname="Serbien und Montenegro" bo_logo="serbienmontenegro.gif" bo_teamtype="1"/>
  <bo_team id="1135" bo_name="Iran" bo_longname="Iran" bo_logo="iran.gif" bo_teamtype="1"/>
  <bo_team id="1136" bo_name="Angola" bo_longname="Angola" bo_logo="angola.gif" bo_teamtype="1"/>
  <bo_team id="1137" bo_name="Ghana" bo_longname="Ghana" bo_logo="ghana.gif" bo_teamtype="1"/>
  <bo_team id="1138" bo_name="Australien" bo_longname="Australien" bo_logo="australien.gif" bo_teamtype="1"/>
  <bo_team id="1139" bo_name="Togo" bo_longname="Togo" bo_logo="togo.gif" bo_teamtype="1"/>
  <bo_team id="1140" bo_name="Ukraine" bo_longname="Ukraine" bo_logo="ukraine.gif" bo_teamtype="1"/>
  <bo_team id="1141" bo_name="FC Bayern München" bo_longname="FC Bayern München" bo_logo="bayern.gif" bo_teamtype="0"/>
  <bo_team id="1142" bo_name="Borussia Dortmund" bo_longname="Borussia Dortmund" bo_logo="bvb.gif" bo_teamtype="0"/>
  <bo_team id="1143" bo_name="Bayer 04 Leverkusen" bo_longname="Bayer 04 Leverkusen" bo_logo="leverkusen.gif" bo_teamtype="0"/>
  <bo_team id="1144" bo_name="SC Freiburg" bo_longname="SC Freiburg" bo_logo="freiburg.gif" bo_teamtype="0"/>
  <bo_team id="1145" bo_name="SV Werder Bremen" bo_longname="SV Werder Bremen" bo_logo="bremen.gif" bo_teamtype="0"/>
  <bo_team id="1146" bo_name="1.FC Kaiserslautern" bo_longname="1.FC Kaiserslautern" bo_logo="lautern.gif" bo_teamtype="0"/>
  <bo_team id="1147" bo_name="VfL Wolfsburg" bo_longname="VfL Wolfsburg" bo_logo="wolfsburg.gif" bo_teamtype="0"/>
  <bo_team id="1148" bo_name="1.FC Köln" bo_longname="1.FC Köln" bo_logo="koeln.gif" bo_teamtype="0"/>
  <bo_team id="1149" bo_name="Hansa Rostock" bo_longname="Hansa Rostock" bo_logo="rostock.gif" bo_teamtype="0"/>
  <bo_team id="1150" bo_name="TSV 1860 München" bo_longname="TSV 1860 München" bo_logo="1860.bmp" bo_teamtype="0"/>
  <bo_team id="1151" bo_name="Hamburger SV" bo_longname="Hamburger SV" bo_logo="hsv.gif" bo_teamtype="0"/>
  <bo_team id="1152" bo_name="Energie Cottbus" bo_longname="Energie Cottbus" bo_logo="cottbus.gif" bo_teamtype="0"/>
  <bo_team id="1153" bo_name="VfB Stuttgart" bo_longname="VfB Stuttgart" bo_logo="stuttgart.gif" bo_teamtype="0"/>
  <bo_team id="1154" bo_name="SpVgg Unterhaching" bo_longname="SpVgg Unterhaching" bo_logo="haching.gif" bo_teamtype="0"/>
  <bo_team id="1155" bo_name="Eintracht Frankfurt" bo_longname="Eintracht Frankfurt" bo_logo="frankfurt.gif" bo_teamtype="0"/>
  <bo_team id="1156" bo_name="VfL Bochum" bo_longname="VfL Bochum" bo_logo="bochum.gif" bo_teamtype="0"/>
  <bo_team id="1157" bo_name="Hertha BSC Berlin" bo_longname="Hertha BSC Berlin" bo_logo="hertha.gif" bo_teamtype="0"/>
  <bo_team id="1158" bo_name="St. Pauli" bo_longname="St. Pauli" bo_logo="stpauli.gif" bo_teamtype="0"/>
  <bo_team id="1159" bo_name="1.FC Nürnberg" bo_longname="1.FC Nürnberg" bo_logo="nuernberg.gif" bo_teamtype="0"/>
  <bo_team id="1160" bo_name="Borussia MGladbach" bo_longname="Borussia Mönchen Gladbach" bo_logo="gladbach.gif" bo_teamtype="0"/>
  <bo_team id="1161" bo_name="FC Schalke 04" bo_longname="FC Schalke 04" bo_logo="schalke.gif" bo_teamtype="0"/>
  <bo_team id="1162" bo_name="Hannover 96" bo_longname="Hannover 96" bo_logo="hannover96.gif" bo_teamtype="0"/>
  <bo_team id="1163" bo_name="Arminia Bielefeld" bo_longname="Arminia Bielefeld" bo_logo="arminiabielefeld.gif" bo_teamtype="0"/>
  <bo_team id="1164" bo_name="FSV Mainz 05" bo_longname="FSV Mainz 05" bo_logo="mainz.gif" bo_teamtype="0"/>
  <bo_team id="1165" bo_name="MSV Duisburg" bo_longname="MSV Duisburg" bo_logo="duisburg.gif" bo_teamtype="0"/>
  <bo_team id="1166" bo_name="Alemannia Aachen" bo_longname="Alemannia Aachen" bo_logo="achen.gif" bo_teamtype="0"/>
  <bo_team id="1167" bo_name="Karlsruher SC" bo_longname="Karlsruher SC" bo_logo="ksc.gif" bo_teamtype="0"/>
  <bo_team id="1168" bo_name="Österreich" bo_longname="Österreich" bo_logo="oesterreich.gif" bo_teamtype="1"/>
  <bo_team id="1169" bo_name="Rumänien" bo_longname="Rumänien" bo_logo="rumaenien.gif" bo_teamtype="1"/>
  <bo_team id="1170" bo_name="1899 Hoffenheim" bo_longname="1899 Hoffenheim" bo_logo="hoffenheim.gif" bo_teamtype="0"/>
  <bo_team id="1171" bo_name="Serbien" bo_longname="Serbien" bo_logo="serbien.gif" bo_teamtype="1"/>
  <bo_team id="1172" bo_name="Algerien" bo_longname="Algerien" bo_logo="algerien.gif" bo_teamtype="1"/>
  <bo_team id="1173" bo_name="Neuseeland" bo_longname="Neuseeland" bo_logo="neuseeland.gif" bo_teamtype="1"/>
  <bo_team id="1174" bo_name="Slowakei" bo_longname="Slowakei" bo_logo="slowakei.gif" bo_teamtype="1"/>
  <bo_team id="1175" bo_name="Nordkorea" bo_longname="Nordkorea" bo_logo="nordkorea.gif" bo_teamtype="1"/>
  <bo_team id="1176" bo_name="Honduras" bo_longname="Honduras" bo_logo="honduras.gif" bo_teamtype="1"/>
